<a href="https://colab.research.google.com/github/stanvanrooy/lab/blob/main/numpy_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [51]:
class Linear:
  def __init__(self, x, y):
    self.x = x
    self.y = y

    self.weights = np.random.randn(y, x)
    self.biases = np.random.randn(y, x)

  def __call__(self, x):
    return np.matmul(self.weights, x)


class Net:
  l1 = Linear(4, 2)

  def forward(self, x):
    x = self.l1(x)
    return x


n = Net()

inp = np.random.randn(4)
out = n.forward(inp)
print(inp, end='\n\n')
print(n.l1.weights, end='\n\n')
print(out)

[-0.89548359 -0.50472211 -0.67359142  1.25243502]
[[ 0.04552512 -0.03179213 -1.28404427 -0.85084213]
 [ 0.82161407 -1.1240937  -0.63369877  1.58473563]]
[[-0.35386419 -0.19893233  2.08322172 -1.62286878]
 [ 1.13519502 -1.64384848  1.26721967  0.50670935]]
[-0.22542408  2.24324548]
